local_costmap:
   global_frame: /odom
   robot_base_frame: /base_link
   update_frequency: 5.0 # 3.0 (5 is pirobot)
   publish_frequency: 2.0 # 1.0
   static_map: false
   rolling_window: true
   width: 6.0
   height: 6.0
   resolution: 0.05
   transform_tolerance: 1.0
   map_type: costmap
